### ISSUE TITLE
can not run npm start

### ISSUE THREAD

**Issue by bewithme** [cycjimmy/jsmpeg-player#127]
**Describe the bug**

**To Reproduce**
1. Go to this project root and open terminal then use env  node v12.22.6 (npm v6.14.15)
2. run npm start
3. see error `[!] Error: 'default' is not exported by package.cjs, imported by rollup/rollup.common.mjs`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 16.04.1-Ubuntu

**Smartphone (please complete the following information):**

**Online demo**
If applicable, provide an online demo to help explain your problem.

**Additional context**

**Comment by cycjimmy** [comment]
You need to upgrade the node to v16 to run the code.
