### ISSUE TITLE
Get video resolution

### ISSUE THREAD

**Issue by ShimaMax** [cycjimmy/jsmpeg-player#14]
Hi. I want to load video and draw it on canvas, but before render I need to set canvas width and height manually. Are the any way to detect video resolution and use this values as canvas width and height if I don't know aspect ratio of the video?

**Comment by cycjimmy** [comment]
Thank you for your issue.
Manually setting the canvas width and height has been discarded in version [3.x](https://github.com/cycdpo/jsmpeg-player/releases/tag/v3.0.1). It is still recommended to manually initialize the size of the wrapper element. You can also configure `autoSetWrapperSize` to `true` to automatically set the wrapper element size to be the same as the video size.
