### ISSUE TITLE
unable to show video after destroy()

### ISSUE THREAD

**Issue by surendragalwa11** [cycjimmy/jsmpeg-player#16]
**Describe the bug**

**To Reproduce**
[https://github.com/surendragalwa111/jsmpeg-player-canvas/blob/master/src/App.js](GithubSnippet)
**Expected behavior**
I have a checkbox to show and hide the video player.
1. Initially checkbox is unchecked and video player doesn't render.
2. When I check the checkbox, I'm able to see the rendered video screen.
3. Now when I uncheck the checkbox to hide the video, I ``destroy()`` the player instance. This works fine but player instance remove all the childElements of ``videoWrapper``
4. Now when I again check the checkbox to render video player, it doesn't render at all.

 WHY??

**Comment by cycjimmy** [comment]
Thanks for your feedback, and sorry for replying so late. I just came back from vacation.

I think manually setting the width and height of the `#canvasParent` element can solve your problem. Just add the following code in your Css.

```css
#canvasParent {
  width: 304px;
  height: 158px;
}
```

**Comment by surendragalwa111** [comment]
But this is not the case.
JSMPEG player attaches an event to destroy the canvas and doesn't unbind the event after the canvas destroyed.

So when we re-render the canvas, the previously attached event again destroys the canvas.This is not something we want.

Please remove this event listener after the destroy() has been completed.

**Comment by cycjimmy** [comment]
I cloned your demo and just manually set the width and height of the #canvasParent element. It seems to achieve the expected behavior. 

Commit: [c17e35](https://github.com/cycdpoCodeLab/jsmpeg-player-canvas/commit/c17e35a2b536a4d7f4ca26a993a6e67dc67ad557)
Preview: https://cycdpocodelab.github.io/jsmpeg-player-canvas/
