### ISSUE TITLE
How can we use it in React ? 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [cycjimmy/jsmpeg-player#17]
Hello , I came to this tool and I am wondering if there is a way that i can use this as a react component . 

Thanks

**Comment by cycjimmy** [comment]
Jsmpeg-player does not support the virtual DOM of React. 
But you can write it directly into the form of the react component. 
I wrote [a simple example](https://github.com/cycjimmy/react-jsmpeg-player-demo) and hope to help you.

Defining component -> [JsmpegPlayer.js](https://github.com/cycjimmy/react-jsmpeg-player-demo/blob/6f96669786ed9f1db027a9e4a388715648dfc30a/src/components/JsmpegPlayer.js)
```javascript
import React, {Component} from 'react';
import JSMpeg from '@cycjimmy/jsmpeg-player';

export default class JsmpegPlayer extends Component {
  constructor(props) {
    super(props);

    this.els = {
      videoWrapper: null,
    };
  };

  render() {
    return (
      <div
        className={this.props.wrapperClassName}
        ref={videoWrapper => this.els.videoWrapper = videoWrapper}>
      </div>
    );
  };

  componentDidMount() {
    // Reference documentation, pay attention to the order of parameters.
    // https://github.com/cycjimmy/jsmpeg-player#usage
    new JSMpeg.VideoElement(
      this.els.videoWrapper,
      this.props.videoUrl,
      this.props.options,
      this.props.overlayOptions
    );
  };
  };
};
```

Using component -> [App.js](https://github.com/cycjimmy/react-jsmpeg-player-demo/blob/6f96669786ed9f1db027a9e4a388715648dfc30a/src/App.js)
```javascript
function App() {
  return (
    ...
        <JsmpegPlayer
          wrapperClassName="video-wrapper"
          videoUrl="..."
          options={...}
          overlayOptions={...}
        />
      ...
  );
}
```

### [Preview](https://cycjimmy.github.io/react-jsmpeg-player-demo/)

**Comment by ahmad-crossplatform** [comment]
Hello @cycjimmy  thanks for your response . 
I am acutually trying to play [this](http://server.shamelforyou.com:5477/live/ahmedmadi/ahm1234/16877.ts) I can play it with VLC  but not really on the web , can you help me understand what happens here ?

**Comment by cycjimmy** [comment]
`jsmpeg-player` is based on [jsmpeg](https://github.com/phoboslab/jsmpeg). You need to confirm if `jsmpeg` works for your TS file.

**Comment by ahmad-crossplatform** [comment]
How do i do that ?

**Comment by cycjimmy** [comment]
> How do i do that ?

See https://github.com/phoboslab/jsmpeg#usage

**Comment by ahmad-crossplatform** [comment]
Thanks !

**Comment by ahmad-crossplatform** [comment]
Thanks !

**Comment by ahmad-crossplatform** [comment]
sorry if I am asking many questions but i am new to this :) 
correct me if I am wrong , but live streaming is now supported , right ?

**Comment by cycjimmy** [comment]
You can use WebSockets to support streaming. 
See: https://github.com/phoboslab/jsmpeg#streaming-via-websockets

**Comment by waleedd32** [comment]
@cycjimmy could you possible create react hooks version of that ? I really need it for live streaming
