### ISSUE TITLE
Full Screen support

### ISSUE THREAD

**Issue by rhscjohn-dev** [cycjimmy/jsmpeg-player#20]
I looked at the demo and the docs and I did not see a full screen button(demo) or an option in the docs.

Is there a technical reason for no support for full screen?  Or is this just something that has not been implemented.

**Comment by cycjimmy** [comment]
Thank you for your suggestion. But in order to keep the feature consistent with `jsmpeg`, I will not add this feature for the time being. You can write a full-screen container and put `videoWrapper` into it temporarily.
