### ISSUE TITLE
Multiple hi-res streams cause chrome to crash

### ISSUE THREAD

**Issue by badders** [cycjimmy/jsmpeg-player#21]
**Describe the bug**
Having ~4 instances of the player running, display 720p/1080p video feeds causes chrome to crash (the Aw, Snap page)

**To Reproduce**

Set up playback for 4 hi resolution streams, wait a few minutes

Streams are encoded with ffmpeg as:

ffmpeg -i rtsp://localhost:8554/ -f mpegts -codec:v mpeg1video -bf 0 -codec:a mp2 -q 1 -nostats -

**Expected behavior**
Not to cause chrome to crash

**Desktop (please complete the following information):**
 - OS: Linux/Windows
 - Browser Chrome
 - Version latest

This may be related to:

https://github.com/phoboslab/jsmpeg/issues/97

**Comment by cycjimmy** [comment]
Suggest reflecting this issue to jsmpeg.
