### ISSUE TITLE
Hiding unmute button

### ISSUE THREAD

**Issue by eulphean** [cycjimmy/jsmpeg-player#23]
I am streaming live webcam video using websockets and jsmpeg player is working great. However, I'm not sending any audio. But, I still see the unmute button when the video starts showing. How can I remove that if I don't want to see it at all? Especially on iOS devices, how can I hide this unmute button?

**Comment by eulphean** [comment]
By setting autoplay to true, the unmute button was hidden.

**Comment by eulphean** [comment]
is there any way to hide this button?

**Comment by eulphean** [comment]
I finally had to send audio: false in overlay properties to hide that button.

**Comment by cycjimmy** [comment]
Sorry for the late reply. Currently, it is not able to manually hide the display of the mute button.
