### ISSUE TITLE
Fix audio only using the right channel for volume

### ISSUE THREAD

**Issue by soonwait** [cycjimmy/jsmpeg-player#24]
as is:
https://github.com/phoboslab/jsmpeg/commit/c5fabf047f1161bcec51bca68ca7c32d377753d8

**Comment by cycjimmy** [comment]
Thanks for your issue. This library has synchronized from https://github.com/phoboslab/jsmpeg/commit/c5fabf047f1161bcec51bca68ca7c32d377753d8 . @soonwait

**Comment by soonwait** [comment]
did you forgot to update src/lib/wasm/WASM_BINARY.js  ???

**Comment by cycjimmy** [comment]
> did you forgot to update src/lib/wasm/WASM_BINARY.js ???

I had updated in https://github.com/cycjimmy/jsmpeg-player/commit/628844febcc75ed6857e421becfbf8fafe72216d .

**Comment by soonwait** [comment]
oh, sorry!

**Comment by cycjimmy** [comment]
u r welcome 😸
