### ISSUE TITLE
memory access out of bounds

### ISSUE THREAD

**Issue by hjl07259** [cycjimmy/jsmpeg-player#27]
error：memory access out of bounds。Excuse me, how should I solve this problem?

**Comment by KidsBen7** [comment]
did you solve this problem? @hjl07259

**Comment by cycjimmy** [comment]
This problem may be related to the encoding of video or the setting of `videoBufferSize`. See the issue in jsmpeg for more information. https://github.com/phoboslab/jsmpeg/issues/268

**Comment by cycjimmy** [comment]
`jsmpeg-player` is based on [jsmpeg](https://github.com/phoboslab/jsmpeg). It is recommended to submit this issue in the `jsmpeg` repo. @felipecrs

**Comment by felipecrs** [comment]
Yes, but there is no indication of which revision of jsmpeg is used here. Is it up to date with the latest jsmpeg upstream?

**Comment by cycjimmy** [comment]
I have just updated to the latest `jsmpeg`.

**Comment by felipecrs** [comment]
@cycjimmy that's awesome! And I wasn't able to reproduce the issue since the update! But let me try it a bit more before concluding anything.

**Comment by felipecrs** [comment]
Ok, this issue happened a lot before. Since the upgrade, I never observed it again. I'm okay to say that it fixed the issue for me.

Thank you!

**Comment by VuIt96** [comment]
I updated to the latest version but still have the same problem
![Capture](https://user-images.githubusercontent.com/50444317/215944800-f1cd3bc9-4fcc-45df-82b5-50577eaf5e8d.PNG)

**Comment by vipulmore01** [comment]
@VuIt96 did you fixed that issue?
