### ISSUE TITLE
live video doesn't play, but local .ts files play fine

### ISSUE THREAD

**Issue by winkmichael** [cycjimmy/jsmpeg-player#281]
**Describe the bug**
loading https://server/video.ts plays, however loading wss://server:444/video/ doesn't play live video.

<VirtualHost *:444>
ProxyPass "/video/" "ws://localhost:8082/"
ProxyPassReverse "/video/" "ws://localhost:8082/"
</VirtualHost

Error: WebSocket connection to 'wss://server:444/video/' failed: An SSL error has occurred and a secure connection to the server cannot be made.

**To Reproduce**
Run the jsmpeg node example, and proxy from apache in front of it to satisfy the SSL.

Any way to make live work? given the wss:// requirement?

**Comment by cycjimmy** [comment]
See https://github.com/phoboslab/jsmpeg#streaming-via-websockets
