### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Mrpsousa** [cycjimmy/jsmpeg-player#29]
Hi, gyus, how can i enable básics controls into the player? i am using on react:

import React, { Component } from 'react';
import JSMpeg from '@cycjimmy/jsmpeg-player';

export default class JsmpegPlayer extends Component {
  constructor(props) {
    super(props);

    this.els = {
      videoWrapper: null,
    };
  };

  render() {
    return (
      <div style={{height:'500px', width:'900px'}}
        className={this.props.wrapperClassName}
        ref={videoWrapper => this.els.videoWrapper = videoWrapper}>
      </div>
    );
  };

  componentDidMount() {
    this.videoPlayer = new JSMpeg.VideoElement(this.els.videoWrapper, this.props.videoUrl, this.props.options, this.props.overlayOptions);
  };

  // pause(){
  //   this.videoPlayer.pause();
  // }
};

and call it that:

 
      <JsmpegPlayer
        wrapperClassName="video-wrapper"
        videoUrl='ws://localhost:9999'
        options={{}}
        overlayOptions={{autoplay: true}}
      />

**Comment by cycjimmy** [comment]
It seems that your code works. And I just enhance the react jsmpeg player demo. https://github.com/cycjimmy/react-jsmpeg-player-demo

**Comment by Mrpsousa** [comment]
Thank you so much, now is working perfectly, sorry for not answered
earlier. Now i need to do  implement a full screen mode.

Em qua., 4 de nov. de 2020 às 04:31, Geoffrey.C <notifications@github.com>
escreveu:

**Comment by cycjimmy** [comment]
This library does not provide full-screen mode. But I think you can control the styles of the video wrapper and canvas elements to meet your needs.

**Comment by vishalkr058** [comment]
Sry for re-opening this issue.
I am using this player in my react application which has many components including live video streaming, but i couldn't able to see the player window as it require `control ` options (Not like **play, pause, stop** button), so how can i use control options in a player. and also how to set height & width inside options?

@cycjimmy if you could help me on this issues.
