### ISSUE TITLE
Setting poster doesn't create an actual poster before playing video. It just shows white screen.

### ISSUE THREAD

**Issue by SWCronSystems-ADOR** [cycjimmy/jsmpeg-player#30]
I am using this package in react app and it's streaming video perfectly but i want to show a poster before the video actually plays.
When i use:
let options = {
 poster: "img.png" //from public folder
}
and then pass it into the VideoElement, it doesn't work. Just shows white screen.

**Comment by cycjimmy** [comment]
Make sure that the path of your poster is correct, and turn on the console to check if there is an error message.
