### ISSUE TITLE
npm 包名能更换吗？携带了@开头，导致和本地 冲突

### ISSUE THREAD

**Issue by shuiche-it** [cycjimmy/jsmpeg-player#302]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cycjimmy** [comment]
很报歉，不方便修改包名，一般来说scoped的包不会与本地产生冲突。您得自行想办法解决本地冲突，或者直接下载源文件进行使用

**Comment by shuiche-it** [comment]
感谢回复，我将源码包下载下来，手动改了包名了。
