### ISSUE TITLE
How to set volume?

### ISSUE THREAD

**Issue by shuiche-it** [cycjimmy/jsmpeg-player#303]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Online demo**
If applicable, provide an online demo to help explain your problem.

**Additional context**

**Comment by cycjimmy** [comment]
JSMpeg.VideoElement.player instance API can view the [JSMpeg.Player API](https://github.com/phoboslab/jsmpeg#jsmpegplayer-api)
